toolbar:
  - insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link uploadimage | forecolor
plugins:
  - link
  - uploadimage
  - textcolor